# Generated by Django 4.0.7 on 2022-09-22 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_agregue_tablas_categorias_figuras_registros'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registro',
            unique_together={('tipo', 'usuario', 'figura')},
        ),
    ]
